/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({ 'faculty' : IDL.Null, 'student' : IDL.Null });
export const Registration = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getRegistration' : IDL.Func([IDL.Principal], [Registration], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Role], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({ 'faculty' : IDL.Null, 'student' : IDL.Null });
  const Registration = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getRegistration' : IDL.Func([IDL.Principal], [Registration], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Role], [], []),
  });
};

export const init = ({ IDL }) => { return []; };